### PR TITLE
Pluralisation rule - words that end in 'i'

### PR DESCRIPTION
**Pull request by katie-roberts**
Hi
I noticed that plural did not pluralise the word chilli.  I have updated the code - and updated the tests.

Thanks for writing a really useful util!

### CODE REVIEW

**Comment by imjacobclark** [comment]
+1

**Comment by swang** [comment]
I think as-is it would cause conflict with words like tsunami, zucchini, alumni, afghani. would you mind changing it to just a direct 1-1 (chilli -> chillis) rule?

**Comment by katie-roberts** [comment]
@swang I have updated - could you please confirm if this is ok now?
thanks

**Comment by swang** [comment]
:+1:

**Pull request merged**
